FROM eclipse-temurin:21-jdk-alpine

# Рабочая директорию
WORKDIR /app

# Копируем jar файл приложения
COPY target/finflow-0.0.1-SNAPSHOT.jar app.jar

# Открываем порт 8080
EXPOSE 8080

# Запускаем приложение
ENTRYPOINT ["java", "-jar", "/app/app.jar"]