spring.application.name=finflow

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/finflow_db
spring.datasource.username=finflow_user
spring.datasource.password=finflow_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.devtools.restart.enabled=false

server.port=8080